### PR TITLE
Fix wrong autofix for non-RegExp arguments in `regexp/prefer-regexp-test` rule

### LINKED ISSUE #119: `prefer-regexp-test` doesn't account for non-RegExp arguments
The `String.prototype.match` function [allows non-RegExp arguments](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/match#a_non-regexp_object_as_the_parameter) which isn't accounted for. This causes incorrect auto fixes.

For more information, see sindresorhus/eslint-plugin-unicorn#1150.

### PR DESCRIPTION
**Pull request by ota-meshi**
Fixed #119

### CODE REVIEW

File: lib/rules/prefer-regexp-test.ts [hunk 1]
```diff
@@ -43,11 +43,14 @@ export default createRule("prefer-regexp-test", {
...
-                    ) {
+                    if (evaluated && evaluated.value instanceof RegExp) {
+                        if (evaluated.value.flags.includes("g")) {
+                            return
+                        }
+                    } else if (!typeTracer.isRegExp(arg)) {
+                        // Not RegExp
+                        // String.prototype.match function allows non-RegExp arguments
+                        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/match#a_non-regexp_object_as_the_parameter
                         return
```
Comment (fisker) [inline lib/rules/prefer-regexp-test.ts:54]: Personally, I'd prefer still report on this case, but remove the auto-fix. 

Because it's just `foo.match(string)` -> `new RegExp(string).test(foo)`, `RegExp#test()` should still suggestted.

Comment (ota-meshi) [reply lib/rules/prefer-regexp-test.ts:54]: Thank you for review! I think your idea is very good!
I will change it.

**Review by RunDevelopment — APPROVED** [review]
